# Generated by Django 3.1 on 2020-09-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLocationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('order', models.IntegerField()),
                ('part_number', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.equipmentmanual')),
                ('site', models.ForeignKey(help_text='The site is the top most ancestor in the location tree. Eg. Auckland', on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_site', to='location.equipmentlocation')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.equipmentlocationcategory')),
            ],
            options={
                'unique_together': {('id', 'site')},
            },
        ),
    ]
